version: "2.4"
services:
  online:
    build: .
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.17"
      ONLINE_MODE: "TRUE"
      MOTD: "LOCALHOST-ONLINE"
      GRACE_PERIOD: "10 s"
  spigot:
    build: .
    ports:
      - 25566:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.16.5"
      ONLINE_MODE: "FALSE"
      MOTD: "LOCALHOST-SPIGOT"
      GRACE_PERIOD: "10 s"
      TYPE: SPIGOT
  bukkit:
    build: .
    ports:
      - 25567:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.16.5"
      ONLINE_MODE: "FALSE"
      MOTD: "LOCALHOST-BUKKIT"
      GRACE_PERIOD: "10 s"
      TYPE: BUKKIT
  offline:
    build: .
    ports:
      - 25568:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.16.5"
      ONLINE_MODE: "FALSE"
      MOTD: "LOCALHOST-OFFLINE"
      GRACE_PERIOD: "10 s"
