name: Docker Image CI

on:
  push:
    branches:
      - "*"

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      MOJANG_USERNAME: ${{ secrets.MOJANG_USERNAME }}
      MOJANG_PASSWORD: ${{ secrets.MOJANG_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install deps
        run: pip3 install -r requirements.txt
      - name: install dev deps
        run: pip3 install -r dev-requirements.txt
      - run: scripts/build-run.sh

